from tkinter import *
import requests
import re
def clicked1():
    requests.get('http://iocontrol.ru/api/sendData/teplica228/window/1')
    btn = Button(window, text="Открыть окно", bg="lime",fg="black", command=clicked1)
    btn.grid(column=0, row=0)
    btn = Button(window, text="Закрыть окно", fg="purple", command=clicked2)
    btn.grid(column=1, row=0)
def clicked2():
    requests.get('http://iocontrol.ru/api/sendData/teplica228/window/0')
    btn = Button(window, text="Открыть окно", fg="lime", command=clicked1)
    btn.grid(column=0, row=0)
    btn = Button(window, text="Закрыть окно", bg="purple",fg="white", command=clicked2)
    btn.grid(column=1, row=0)
def clicked3():
        requests.get('http://iocontrol.ru/api/sendData/teplica228/pump/1')
        btn = Button(window, text="Включить полив", bg="lime", fg="black", command=clicked3)
        btn.grid(column=0, row=1)
        btn = Button(window, text="Выключить полив", fg="purple", command=clicked4)
        btn.grid(column=1, row=1)
def clicked4():
        requests.get('http://iocontrol.ru/api/sendData/teplica228/pump/0')
        btn = Button(window, text="Включить полив", fg="lime", command=clicked3)
        btn.grid(column=0, row=1)
        btn = Button(window, text="Выключить полив", bg="purple", fg="white", command=clicked4)
        btn.grid(column=1, row=1)
def clicked5():
    requests.get('http://iocontrol.ru/api/sendData/teplica228/wind/1')
    btn = Button(window, text="Включить вентилятор", bg="lime", fg="black", command=clicked5)
    btn.grid(column=0, row=2)
    btn = Button(window, text="Выключить вентилятор", fg="purple", command=clicked6)
    btn.grid(column=1, row=2)
def clicked6():
    requests.get('http://iocontrol.ru/api/sendData/teplica228/wind/0')
    btn = Button(window, text="Включить вентилятор", fg="lime", command=clicked5)
    btn.grid(column=0, row=2)
    btn = Button(window, text="Выключить вентилятор", bg="purple", fg="white", command=clicked6)
    btn.grid(column=1, row=2)
def clicked7():
    requests.get('http://iocontrol.ru/api/sendData/teplica228/svetred/1')
    btn = Button(window, text="Включить нагрев", bg="lime", fg="black", command=clicked7)
    btn.grid(column=0, row=3)
    btn = Button(window, text="Выключить нагрев", fg="purple", command=clicked8)
    btn.grid(column=1, row=3)
def clicked8():
    requests.get('http://iocontrol.ru/api/sendData/teplica228/svetred/0')
    btn = Button(window, text="Включить нагрев", fg="lime", command=clicked7)
    btn.grid(column=0, row=3)
    btn = Button(window, text="Выключить нагрев", bg="purple", fg="white", command=clicked8)
    btn.grid(column=1, row=3)
def clicked9():
    requests.get('http://iocontrol.ru/api/sendData/teplica228/svetyellow/1')
    btn = Button(window, text="Включить обеззараживание", bg="lime", fg="black", command=clicked9)
    btn.grid(column=0, row=4)
    btn = Button(window, text="Выключить обеззараживание", fg="purple", command=clicked10)
    btn.grid(column=1, row=4)
def clicked10():
    requests.get('http://iocontrol.ru/api/sendData/teplica228/svetyellow/0')
    btn = Button(window, text="Включить обеззараживание", fg="lime", command=clicked9)
    btn.grid(column=0, row=4)
    btn = Button(window, text="Выключить обеззараживание", bg="purple", fg="white", command=clicked10)
    btn.grid(column=1, row=4)
def reset():
    BASE_URL = 'http://iocontrol.ru/api/readData/teplica228/temp'
    response = requests.get(BASE_URL)
    t = str(response.json())
    number = re.search(r'\d+', t).group()
    lbl = Label(window, text=f'{number}°C')
    lbl.grid(column=0, row=6)
    BASE_URL = 'http://iocontrol.ru/api/readData/teplica228/hud'
    response = requests.get(BASE_URL)
    t = str(response.json())
    number = re.search(r'\d+', t).group()
    lbl = Label(window, text=f'{number}%')
    lbl.grid(column=1, row=6)
    BASE_URL = 'http://iocontrol.ru/api/readData/teplica228/hud_d'
    response = requests.get(BASE_URL)
    t = str(response.json())
    number = re.search(r'\d+', t).group()
    lbl = Label(window, text=f'{number}%')
    lbl.grid(column=1, row=8)
    BASE_URL = 'http://iocontrol.ru/api/readData/teplica228/temp_d'
    response = requests.get(BASE_URL)
    t = str(response.json())
    number = re.search(r'\d+', t).group()
    lbl = Label(window, text=f'{number}°C')
    lbl.grid(column=0, row=8)
    BASE_URL = 'http://iocontrol.ru/api/readData/teplica228/osvet'
    response = requests.get(BASE_URL)
    t = str(response.json())
    number = re.search(r'\d+', t).group()
    lbl = Label(window, text=f'{number} lux')
    lbl.grid(column=0, row=10)
window = Tk()
window.title("Управление теплицей")
window.geometry('400x420')
btn = Button(window, text="Открыть окно", command=clicked1)
btn.grid(column=0, row=0)
btn = Button(window, text="Закрыть окно", command=clicked2)
btn.grid(column=1, row=0)
btn = Button(window, text="Включить полив", command=clicked3)
btn.grid(column=0, row=1)
btn = Button(window, text="Выключить полив", command=clicked4)
btn.grid(column=1, row=1)
btn = Button(window, text="Включить вентилятор", command=clicked5)
btn.grid(column=0, row=2)
btn = Button(window, text="Выключить вентилятор", command=clicked6)
btn.grid(column=1, row=2)
btn = Button(window, text="Включить нагрев", command=clicked7)
btn.grid(column=0, row=3)
btn = Button(window, text="Выключить нагрев", command=clicked8)
btn.grid(column=1, row=3)
btn = Button(window, text="Включить обеззараживание", command=clicked9)
btn.grid(column=0, row=4)
btn = Button(window, text="Выключить обеззараживание", command=clicked10)
btn.grid(column=1, row=4)
btn = Button(window, text="Обновить", command=reset)
btn.grid(column=3, row=0)
lbl = Label(window, text='Температура')
lbl.grid(column=0, row=5)
lbl = Label(window, text='Влажность')
lbl.grid(column=1, row=5)
lbl = Label(window, text='Влажность почвы')
lbl.grid(column=1, row=7)
lbl = Label(window, text='Освещённость')
lbl.grid(column=0, row=9)
lbl = Label(window, text='Температура почвы')
lbl.grid(column=0, row=7)
window.mainloop()
